package main

import (
	"fmt"
)

func main() {
	i := 2
	var seq = make(map[int]int)
	seq[0], seq[1] = 1, 2
	for {
		seq[i] = seq[i-1] + seq[i-2]
		if seq[i] > 4000000 {
			break
		}
		i++
	}

	var sum int

	for i := 0; i <= len(seq); i++ {
		if seq[i]%2 == 0 {
			sum += seq[i]
		}
	}

	fmt.Println(len(seq))
	fmt.Println(sum)
}

/*
Even Fibonacci numbers
Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
